Reindex cases in elasticsearch
powsybl/powsybl-case pull request #85
Opened 2022-04-13 14:55 UTC by FranckLecuyer

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the current behavior?** *(You can also link to an open issue here)*
 Unable to manually reindex the cases data in elasticsearch

**What is the new behavior (if this is a feature change)?**
 A rest API is now available to manually reindex the cases data in elasticsearch

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-04-25 10:44 UTC, niconoir requested changes

2022-04-25 10:44 UTC, niconoir commented on case-server/src/main/java/com/powsybl/caseserver/CaseController.java
> +    @PostMapping(value = "/cases/reindex-all")
Why not use POST /cases/indexes ?

2022-04-25 11:24 UTC, FranckLecuyer commented on case-server/src/main/java/com/powsybl/caseserver/CaseController.java
> +    @PostMapping(value = "/cases/reindex-all")
I used the API defined in the US

2022-04-28 13:33 UTC, niconoir approved these changes

2022-05-02 08:39 UTC, laurgarn approved these changes

2022-05-02 11:54 UTC, jonenst approved these changes

2022-05-02 12:34 UTC, merged